
"""add storage_path to rag_documents

Revision ID: fec1e50298cd
Revises: 8dfc24fb06cb
Create Date: 2026-03-20 14:58:25.759460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fec1e50298cd'
down_revision: Union[str, None] = '8dfc24fb06cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_documents', 'storage_path')
    # ### end Alembic commands ###
