
"""add rag_documents table

Revision ID: 8dfc24fb06cb
Revises: 947b4e7d93fb
Create Date: 2026-03-20 14:28:47.153090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dfc24fb06cb'
down_revision: Union[str, None] = '947b4e7d93fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vector_document_id', sa.String(length=255), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rag_documents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_documents_pkey'))
    )
    op.create_index(op.f('rag_documents_collection_name_idx'), 'rag_documents', ['collection_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('rag_documents_collection_name_idx'), table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
